# permissions for end users to view clouds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloud-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatorctf
    app.kubernetes.io/part-of: operatorctf
    app.kubernetes.io/managed-by: kustomize
  name: cloud-viewer-role
rules:
- apiGroups:
  - ctf.securinetes.com
  resources:
  - clouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ctf.securinetes.com
  resources:
  - clouds/status
  verbs:
  - get
